### ISSUE TITLE
Cannot assign to read only property '__esModule' of object '#<Object>' 

### ISSUE THREAD

**Issue by Zhao-LiZhong** [Kennytian/graphql-wechat#1]
taro调用apollo-boost报错
Cannot assign to read only property '__esModule' of object '#<Object>' 
TypeError: Cannot assign to read only property '__esModule' of object '#<Object>'
微信小程序调试基础库2.7.2
非常感谢🙏，帮帮忙

**Comment by Kennytian** [comment]
@Zhao-LiZhong 已经更新到最新 Taro 1.3.19 版本了，你再试试！
